@ECHO OFF
C:\BP\BIN\TASM /oi /m BIOS_PNP.ALP
LINK386 /NOLOGO /ALIGNMENT:1 BIOS_PNP.OBJ,BIOS_PNP.SYS,BIOS_PNP.MAP,,BIOS_PNP.DEF
IF EXIST BIOS_PNP.OBJ DEL BIOS_PNP.OBJ
IF EXIST BIOS_PNP.MAP DEL BIOS_PNP.MAP
IF EXIST BIOS_PNP.SYM DEL BIOS_PNP.SYM