@ECHO OFF
CLS
ALP +Od -Mb +Sfs BIOS_PNP.ALP
IF ERRORLEVEL 1 PAUSE
LINK386 /MAP:FULL /NOLOGO /ALIGNMENT:1 BIOS_PNP.OBJ,BIOS_PNP.SYS,BIOS_PNP.MAP,,BIOS_PNP.DEF
CALL NOEA BIOS_PNP.SYS
MAPSYM -n BIOS_PNP > NUL 2>&1
IF EXIST BIOS_PNP.OBJ DEL BIOS_PNP.OBJ
IF EXIST BIOS_PNP.MAP DEL BIOS_PNP.MAP
CALL LX /F+ /U+ /ZS /T BIOS_PNP.SYS
rem CALL LX /F+ /U+ /X /ZS /T BIOS_PNP.SYS 
copy BIOS_PNP.S?? ..\..\